name: offline_first_design
description: "Project with Offline First Design."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get_it: ^8.0.0
  provider: ^6.1.2
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_ce_generator: ^1.11.1

flutter:
  uses-material-design: true
